import type { CarryItem, CatalogItem } from "./recipes";

export function carryEmoji(item: CarryItem | null): string {
	return item ? CATALOG_EMOJI[item] : "";
}

export const CATALOG_LABELS: Record<CatalogItem, string> = {
	bun: "булка",
	baguette: "багет",
	pita: "пита",
	lettuce: "салат",
	tomato: "помидор",
	onion: "лук",
	potato: "картофель",
	carrot: "морковь",
	mushrooms: "грибы",
	pepper: "перец",
	cucumber: "огурец",
	corn: "кукуруза",
	lemon: "лимон",
	cheese: "сыр",
	egg: "яйцо",
	cream: "сливки",
	butter: "сливочное масло",
	flour: "мука",
	pasta: "сухая паста",
	rice: "рис",
	broth: "бульон",
	"olive-oil": "оливковое масло",
	beans: "фасоль",
	mince: "фарш",
	chicken: "курица",
	sausage: "сосиска",
	bacon: "бекон",
	"chopped-lettuce": "нарезанный салат",
	"chopped-tomato": "нарезанный помидор",
	"chopped-onion": "нарезанный лук",
	"chopped-potato": "нарезанный картофель",
	"chopped-carrot": "нарезанная морковь",
	"chopped-mushrooms": "нарезанные грибы",
	"chopped-pepper": "нарезанный перец",
	"chopped-cucumber": "нарезанный огурец",
	"chopped-corn": "нарезанная кукуруза",
	patty: "котлета",
	"fried-chicken": "жареная курица",
	"fried-sausage": "жареная сосиска",
	"crispy-bacon": "хрустящий бекон",
	dough: "тесто",
	"pizza-base": "основа пиццы",
	toast: "тост",
	"hot-broth": "горячий бульон",
	"tomato-sauce": "томатный соус",
	"dish-burger": "бургер",
	"dish-pizza": "пицца",
	"dish-hotdog": "хот-дог",
	"dish-soup": "суп",
	"dish-salad": "салат",
	"dish-pasta": "паста",
	"dish-rice": "рис",
	"dish-sandwich": "сэндвич",
	"dish-shawarma": "шаурма",
	"dish-bruschetta": "брускета",
	"dish-omelette": "омлет",
};

export const CATALOG_EMOJI: Record<CatalogItem, string> = {
	bun: "🍞",
	baguette: "🥖",
	pita: "🫓",
	lettuce: "🥬",
	tomato: "🍅",
	onion: "🧅",
	potato: "🥔",
	carrot: "🥕",
	mushrooms: "🍄",
	pepper: "🫑",
	cucumber: "🥒",
	corn: "🌽",
	lemon: "🍋",
	cheese: "🧀",
	egg: "🥚",
	cream: "🥛",
	butter: "🧈",
	flour: "🌾",
	pasta: "🍝",
	rice: "🍚",
	broth: "🥣",
	"olive-oil": "🫒",
	beans: "🫘",
	mince: "🥩",
	chicken: "🐔",
	sausage: "🌭",
	bacon: "🥓",
	"chopped-lettuce": "🥬",
	"chopped-tomato": "🍅",
	"chopped-onion": "🧅",
	"chopped-potato": "🥔",
	"chopped-carrot": "🥕",
	"chopped-mushrooms": "🍄",
	"chopped-pepper": "🫑",
	"chopped-cucumber": "🥒",
	"chopped-corn": "🌽",
	patty: "🍖",
	"fried-chicken": "🍗",
	"fried-sausage": "🌭",
	"crispy-bacon": "🥓",
	dough: "🥠",
	"pizza-base": "🥞",
	toast: "🧇",
	"hot-broth": "🍲",
	"tomato-sauce": "🥫",
	"dish-burger": "🍔",
	"dish-pizza": "🍕",
	"dish-hotdog": "🌭",
	"dish-soup": "🍜",
	"dish-salad": "🥗",
	"dish-pasta": "🍝",
	"dish-rice": "🍛",
	"dish-sandwich": "🥪",
	"dish-shawarma": "🌯",
	"dish-bruschetta": "🥖",
	"dish-omelette": "🍳",
};
